spring:
  datasource:
    url: jdbc:h2:mem:payment_transfer_application;;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  flyway:
    locations: classpath:db/migration
server:
  error:
    include-message: always
accounts:
  mini-statement:
    size: 20

token:
  # Token valid time, unit minute 24*60=1440
  tokenExpireTime: 1440
  # Update the token time 2*60=120
  refreshCheckTime: 120
  # RefreshToken expiration time，unit minute 24*60=1440
  refreshTokenExpireTime: 1440
  # Shiro cache expiry date，unit minute, 2*60=120
  shiroCacheExpireTime: 120
  # Token encryption key
  secretKey: peterw3
